### PR TITLE
fix verify false and add tests

### LINKED ISSUE #1718: Berkshelf SSL Validation Failed (regression?)
With Berkshelf 6.2.1 I'm getting error:
```
Fetching cookbook index from https://supermarket.domain.local...
[2017-07-31T16:04:42+03:00] ERROR: SSL Validation failure connecting to host: supermarket.domain.local - SSL_connect returned=1 errno=0 state=error: certificate verify failed
/home/sirex/.rvm/gems/ruby-2.3.3/gems/chef-12.21.1/lib/chef/http.rb:412:in `rescue in retrying_http_errors': SSL Error connecting to https://supermarket.domain.local/universe - SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
        from /home/sirex/.rvm/gems/ruby-2.3.3/gems/chef-12.21.1/lib/chef/http.rb:369:in `retrying_http_errors'
        from /home/sirex/.rvm/gems/ruby-2.3.3/gems/chef-12.21.1/lib/chef/http.rb:333:in `send_http_request'
        from /home/sirex/.rvm/gems/ruby-2.3.3/gems/chef-12.21.1/lib/chef/http.rb:148:in `request'
        from /home/sirex/.rvm/gems/ruby-2.3.3/gems/chef-12.21.1/lib/chef/http.rb:115:in `get'
        from /home/sirex/.rvm/gems/ruby-2.3.3/gems/berkshelf-6.2.1/lib/berkshelf/ridley_compat.rb:26:in `get'
        from /home/sirex/.rvm/gems/ruby-2.3.3/gems/berkshelf-6.2.1/lib/berkshelf/api_client/connection.rb:46:in `universe'
        from /home/sirex/.rvm/gems/ruby-2.3.3/gems/berkshelf-6.2.1/lib/berkshelf/source.rb:85:in `build_universe'
        from /home/sirex/.rvm/gems/ruby-2.3.3/gems/berkshelf-6.2.1/lib/berkshelf/installer.rb:24:in `block (2 levels) in build_universe'
```

It worked with berkshelf 6.1.1, but now for 6.1.1 I'm getting another error:
```
/home/sirex/.rvm/gems/ruby-2.4.0/gems/solve-3.1.0/lib/solve/ruby_solver.rb:80:in `block in resolve': undefined method `name' for nil:NilClass (NoMethodError)
        from /home/sirex/.rvm/gems/ruby-2.4.0/gems/solve-3.1.0/lib/solve/ruby_solver.rb:79:in `each'
        from /home/sirex/.rvm/gems/ruby-2.4.0/gems/solve-3.1.0/lib/solve/ruby_solver.rb:79:in `inject'
        from /home/sirex/.rvm/gems/ruby-2.4.0/gems/solve-3.1.0/lib/solve/ruby_solver.rb:79:in `resolve'
        from /home/sirex/.rvm/gems/ruby-2.4.0/gems/solve-3.1.0/lib/solve.rb:64:in `it!'
        from /home/sirex/.rvm/gems/ruby-2.4.0/gems/berkshelf-6.1.1/lib/berkshelf/resolver.rb:78:in `resolve'
        from /home/sirex/.rvm/gems/ruby-2.4.0/gems/berkshelf-6.1.1/lib/berkshelf/installer.rb:181:in `install_from_universe'
        from /home/sirex/.rvm/gems/ruby-2.4.0/gems/berkshelf-6.1.1/lib/berkshelf/installer.rb:43:in `run'
        from /home/sirex/.rvm/gems/ruby-2.4.0/gems/berkshelf-6.1.1/lib/berkshelf/berksfile.rb:426:in `install'
        from /home/sirex/.rvm/gems/ruby-2.4.0/gems/berkshelf-6.1.1/lib/berkshelf/cli.rb:140:in `install'
        from /home/sirex/.rvm/gems/ruby-2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/sirex/.rvm/gems/ruby-2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/sirex/.rvm/gems/ruby-2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/sirex/.rvm/gems/ruby-2.4.0/gems/berkshelf-6.1.1/lib/berkshelf/cli.rb:49:in `dispatch'
        from /home/sirex/.rvm/gems/ruby-2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/sirex/.rvm/gems/ruby-2.4.0/gems/berkshelf-6.1.1/lib/berkshelf/cli.rb:25:in `execute!'
        from /home/sirex/.rvm/gems/ruby-2.4.0/gems/berkshelf-6.1.1/bin/berks:5:in `<top (required)>'
        from /home/sirex/.rvm/gems/ruby-2.4.0/bin/berks:23:in `load'
        from /home/sirex/.rvm/gems/ruby-2.4.0/bin/berks:23:in `<main>'
        from /home/sirex/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
        from /home/sirex/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```
Gemfile:
```ruby
# frozen_string_literal: true

source 'https://rubygems.org'

gem 'chef', '~> 12.14'

group :lint do
  gem 'foodcritic'
  gem 'rubocop'
end

group :unit do
  gem 'berkshelf'
  gem 'chefspec'
  gem 'ci_reporter_rspec'
end

group :development do
  gem 'pry'
  gem 'pry-byebug'
  gem 'rake'
  gem 'stove'
end

group :knife do
  gem 'knife-cookbook-doc'
  gem 'knife-supermarket'
end

# Kitchen
group :kitchen do
  gem 'kitchen-docker'
  gem 'kitchen-inspec'
  gem 'kitchen-sync'
  gem 'kitchen-vagrant'
  gem 'test-kitchen'
end

group :guard do
  gem 'guard'
  gem 'guard-bundler', require: false
  gem 'guard-foodcritic', require: false
  gem 'guard-kitchen', require: false
  gem 'guard-rspec', require: false
  gem 'guard-rubocop', require: false
end
```

~/.berkshelf/config.json:
```json
{
  "ssl": {
    "verify": false
  }
}
```
Also I tried ruby-2.3.3, ruby-2.4.0 and ruby-2.4.1

### PR DESCRIPTION
**Pull request by lamont-granquist**
i think this fixes it, there were bugs stacked on top of bugs here.

this adds some tests that are more functional-ish than unit-ey and caught the fact that the SSLPolicies stuff inside of chef-client itself reads directly from Chef::Config and the constructor for the Chef::HTTP derived object has no control over those settings.

closes #1718

### CODE REVIEW

**Comment by lamont-granquist** [comment]
appveyor busted because appveyor still.  happily removing celluloid and ridley in the other PR will get that back to green again...
